#
# (C) Copyright 2013-2021 Xilinx, Inc.
# (C) Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
namespace export *


#
# It will return the software common::version.
# Note: Mostly it is used when some new file need to be generated through HSI
#
proc get_sw_build_version { } {
    set ret [common::hsi version -short]
}

#
# It will return the copyright message along with software common::version
# Note: Mostly it is used when some new file need to be generated through HSI
#
proc get_copyright_msg { } {
    set copyright_str "Copyright (C) 2010-"
    append copyright_str [clock format [clock seconds] -format %Y]
    append copyright_str " Xilinx, Inc. All Rights Reserved."
    append copyright_str "\n"
    append copyright_str "* SPDX-License-Identifier: MIT "
    append copyright_str "\n"
#    append copyright_str "*\n"
#    append copyright_str "*Permission is hereby granted, free of charge, to any person obtaining a copy\n"
#     append copyright_str "*of this software and associated documentation files (the Software), to deal\n"
#     append copyright_str "*in the Software without restriction, including without limitation the rights\n"
#      append copyright_str "*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
#      append copyright_str "*copies of the Software, and to permit persons to whom the Software is\n" 
#      append copyright_str "*furnished to do so, subject to the following conditions:\n"
#    append copyright_str "*\n"
#    append copyright_str "*The above copyright notice and this permission notice shall be included in\n"
#     append copyright_str "*all copies or substantial portions of the Software.\n"
#    append copyright_str "* \n"
#    append copyright_str "*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
#     append copyright_str "*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
#      append copyright_str "*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL \n"
#      append copyright_str "*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\n"
#      append copyright_str "*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT\n"
#       append copyright_str "*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
#    append copyright_str "*\n"

    return $copyright_str
}
#
# Print standard Xilinx header for .h/.c files
#
proc write_c_header {file_handle  desc} {
    puts $file_handle "
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: [get_sw_build_version]
* DO NOT EDIT.
*
* [get_copyright_msg]
* 
* Description: $desc
*
*******************************************************************/
"
}

#
# Print standard Xilinx header for .tcl files
#
proc write_tcl_header {file_handle  desc} {
    puts $file_handle "
# ------------------------------------------------------------------
#
# CAUTION: This file is automatically generated by HSI.
# Version: [get_sw_build_version]
# DO NOT EDIT.
#
# [get_copyright_msg]
# 
# Description: $desc
#
# ------------------------------------------------------------------
"
}


#
# get the special format for the address parameters which has special string in parameter value. 
#
proc format_addr_string {value param_name} {
   if {[string match *_BASEADDR $param_name] || [string match *_HIGHADDR $param_name] || [string compare -nocase $param_name "C_KIND_OF_INTR"] == 0 } {
       set value [format_address_string $value]
   }
   return $value
}

#
# get the hex format string of input value
#
proc format_address_string {value} {
   # remove _ from string
   set value [string map {_ ""} $value]
   # Check to see if value starts with 0b or 0x
   if {[string match -nocase 0b* $value]} {
       set value [convert_binary_to_hex $value]
   } else {
       set value [format "0x%08llX" $value]
   }
   return $value
}

#
# Convert a binary number to a hex value.  The binary string must be of the form 0b*.  
# The returned hex string is of the form 0x*
#
proc convert_binary_to_hex {value} {
   # remove _ from string
   set value [string map {_ ""} $value]
   
   if {[regexp -nocase {^0b[01]+$} $value]} {
       set value [format "%032s" [string range $value 2 end]]
       set return_value "0x"
       for {set i 0} {$i < 8} {incr i 1} {
           set substr [string range $value [expr $i * 4] [expr ($i * 4)+3]]
           set char 0
           set val 8
           for {set j 0} {$j < 4} {incr j 1} {
               set char [expr (($val >> $j) * [string range $substr $j $j]) + $char]
           }
           set return_value [format "%s%1X" $return_value $char]
       }
       return $return_value
   } else {
       error "convert_binary_to_hex expects a binary string of the form 0b<binary string>." "" "hsi_error"
       return
   }
}
#
# Convert a binary number to a decimal value.  The binary string must be of the form 0b*.  
#

#
# Convert a number to binary value. 
# Input number can be either integer or hex
# The returned binary value will be prefixed with 0b
# length of the binary value should be specified 
# e.g. if input value is 2, and length is 5, then return value will be 0b00010
#
proc convert_num_to_binary {value length} {
   if {$length == 0} {
       error "convert_num_to_binary expects lenght to be a positive number" "" "mdt_error"
       return
   }

   # remove _ from string
   set value [string map {_ ""} $value]

   set retval ""
   while {$value > 0} {
   set tval [expr $value + 1]
   set val_by_2 [expr $value/2]
   set tval_by_2 [expr $tval/2]
   if {$val_by_2 == $tval_by_2} {
       # means $val is even
       set retval [format "0%s" $retval]
   } else {
       # means $val is odd
       set retval [format "1%s" $retval]
   }
   set value [expr $value/2]
   }

   while {$length > [string length $retval]} {
   set retval [format "0%s" $retval]
   }

   set retval [format "0b%s" $retval]
   return $retval
}

#
# return  1 if $base_addr > $high_addr
# return  0 if $base_addr = $high_addr
# return -1 if $base_addr < $high_addr
#

#
# Procedure to determine the host os platform
# Possible Return values: lnx, lnx64, win, win64
#
proc get_hostos_platform { } {
   global tcl_platform env tcl_library
   set plat_os $env(RDI_PLATFORM)
   return $plat_os
}

#
# Procedure to determine the executable suffix
# Possible Return values: 
#          "dll"  on windows
#          "so"   on linux
#
proc get_hostos_sharedlib_suffix { } {
   global tcl_platform env tcl_library

   switch -glob $tcl_platform(os) {
   "Windows*" {
       set suffix "dll"
   }
   "Linux" {
       set suffix "so"
   }
   default {
       error "Unsupport OS\n" "" "mdt_error"
   }
   }

   return $suffix
}

#
# Procedure to find file within a list of given 
# directories. The path provided should be
# relative with respect to the input directories
#
proc find_file_in_dirs { dirlist relative_filepath } {
   foreach dir $dirlist {
   set filepath [format "%s/%s" $dir $relative_filepath]
   if { [file exists $filepath] } {
       return $filepath
   }
   }
   ## file not found in any directory
   return ""
}

#
# Procedure to locate a specific file within Xilinx
# tool install. The procedure takes relative path
# with respect to the install area
#
proc find_file_in_xilinx_install { relative_filepath } {
   set dirlist ""

   ## $XILINX can be a list of directories
   if [ info exists ::env(XILINX) ] {
   set xildirs ""
   global tcl_platform env tcl_library
   switch -glob $tcl_platform(os) {
       "Windows*" {
            set xildirs [split $::env(XILINX) ";"]
       }
       "Linux" {
            set xildirs [split $::env(XILINX) ":"]
       }
       default {
            error "Unsupport OS\n" "" "mdt_error"
       }
   }
   foreach xildir $xildirs {
       lappend dirlist $xildir
   }
   } 
   return [find_file_in_dirs $dirlist $relative_filepath]
}
